feat(Schema): add "getFor" and "getPrimaryKey" methods
Hypheme/harmonized.js pull request #25
Opened 2017-01-08 21:05 UTC by tchock

Added these two methods to schema:
* **getFor():** gets item in the format needed for the target
* **getPrimaryKey():** gets primary key for target

fixes #5

2017-01-08 22:38 UTC, JohannesMerz requested changes

2017-01-08 22:38 UTC, JohannesMerz commented on src/Schema.js
> +    return item.onceReadyFor(source).then(() => {
this is wrong. We need this even if the item has no keys (for example when creating it, we need the data anyway). 

You need to do this for all foreign Items further down (as they need to exist in the target before we can use them - for example when you asign a driver to a car, the driver has to exist in the transporter before he can be assigned to the car)

2017-01-08 23:19 UTC, JohannesMerz commented on src/Schema.js
> +    return item.onceReadyFor(source).then(() => {
update:
there will be a sync. ( #26 )
`boolean item.isReadyFor(target)` which returns true or false
+ will change 
`promise item.onceReady(source)` to `promise item.onceReady(target)`
as you need this this way.

2017-01-09 22:29 UTC, tchock commented on src/Schema.js
> +    return item.onceReadyFor(source).then(() => {
Ah ok, so this means, the actual getFor() is always synchronous and it is wrapped by an async check for the relational items to be ready.

This isn't that hard. Will solve this until the end of the week :)

2017-01-09 22:52 UTC, JohannesMerz commented on src/Schema.js
> +    return item.onceReadyFor(source).then(() => {
yes. Note that the async wrapper has to be recursive and the initial check if everything is ready needs to be synchronous (same tick as the returned data if everything is ready). I Agree its not hard to implement, just a bit tricky to get at first.

2017-01-10 09:00 UTC, tchock commented
Updated it, but tests are need to be rewritten for this. This is just for review purposes.

2017-01-10 09:43 UTC, JohannesMerz reviewed
other than that looks good

2017-01-10 09:43 UTC, JohannesMerz commented on src/Schema.js
> +          .filter(refItem => !refItem.isReadyFor(target))
can't you use one reduce instead of map + filter

2017-01-14 19:25 UTC, JohannesMerz approved these changes

2017-01-14 19:29 UTC, merged